# Generated by Django 5.2.15 on 2026-07-15 08:57

from django.db import migrations, models


def approve_existing_restaurants(apps, schema_editor):
    Restaurant = apps.get_model('core', 'Restaurant')
    Restaurant.objects.update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hash_existing_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.RunPython(approve_existing_restaurants, migrations.RunPython.noop),
    ]
